none:
  callable: null
  params: {}

gan:
  callable: ids_research.attacks.whitebox.gan_attack:run_gan_attack
  params: {}

fgsm:
  callable: ids_research.attacks.whitebox.fast_gradient:run_fgsm_attack
  params:
    epsilon: 0.05
    clip_min: 0.0
    clip_max: 1.0

pgd:
  callable: ids_research.attacks.whitebox.fast_gradient:run_pgd_attack
  params:
    epsilon: 0.05
    step_size: 0.01
    pgd_steps: 10
    clip_min: 0.0
    clip_max: 1.0
